<?xml version="1.0"?>
<!--
  RC car robot description using URDF with xacro macros.

  Dimensions are representative of a 1/10-scale RC car:
    - Wheelbase: 0.30 m
    - Track width: 0.20 m
    - Body: 0.40 m × 0.20 m × 0.10 m
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rc_car">

  <!-- ================================================================== -->
  <!-- Properties                                                          -->
  <!-- ================================================================== -->
  <xacro:property name="wheelbase"     value="0.30"/>
  <xacro:property name="track_width"   value="0.20"/>
  <xacro:property name="wheel_radius"  value="0.05"/>
  <xacro:property name="wheel_width"   value="0.04"/>
  <xacro:property name="body_length"   value="0.40"/>
  <xacro:property name="body_width"    value="0.20"/>
  <xacro:property name="body_height"   value="0.10"/>
  <xacro:property name="chassis_mass"  value="1.5"/>
  <xacro:property name="wheel_mass"    value="0.1"/>

  <!-- ================================================================== -->
  <!-- Macros                                                              -->
  <!-- ================================================================== -->

  <!-- Inertia tensor for a solid box -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <inertia
        ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
        iyy="${m*(x*x+z*z)/12}" iyz="0"
        izz="${m*(x*x+y*y)/12}"/>
    </inertial>
  </xacro:macro>

  <!-- Inertia tensor for a solid cylinder (axis = Z) -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia
        ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
        iyy="${m*(3*r*r+h*h)/12}" iyz="0"
        izz="${m*r*r/2}"/>
    </inertial>
  </xacro:macro>

  <!-- Wheel macro (rear wheels only – no steering) -->
  <xacro:macro name="wheel" params="name parent x y">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="dark_grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="${parent}"/>
      <child  link="${name}"/>
      <!-- Wheels spin about their own Y axis; shift by 90° so the cylinder
           axis aligns with the vehicle lateral axis. -->
      <origin xyz="${x} ${y} 0" rpy="${pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- Front steered-wheel macro.
       Creates a steering link (revolute about Z) attached to the chassis, then
       attaches the spinning wheel to that steering link.
       Joint naming convention:
         ${name}_steering_joint  – revolute, steers the wheel left/right
         ${name}_joint           – continuous, spins the wheel            -->
  <xacro:macro name="front_wheel" params="name parent x y">
    <!-- Steering link (massless pivot) -->
    <link name="${name}_steering_link">
      <xacro:box_inertia m="0.01" x="0.01" y="0.01" z="0.01"/>
    </link>
    <joint name="${name}_steering_joint" type="revolute">
      <parent link="${parent}"/>
      <child  link="${name}_steering_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.6" upper="0.6" effort="10" velocity="1.0"/>
    </joint>

    <!-- Wheel itself (spins about its own axis) -->
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="dark_grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="${name}_steering_link"/>
      <child  link="${name}"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- ================================================================== -->
  <!-- Base link (reference frame at centre of rear axle, ground level)   -->
  <!-- ================================================================== -->
  <link name="base_link"/>

  <!-- ================================================================== -->
  <!-- Chassis                                                             -->
  <!-- ================================================================== -->
  <link name="chassis">
    <visual>
      <origin xyz="${wheelbase/2} 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${wheelbase/2} 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${chassis_mass}"
                       x="${body_length}" y="${body_width}" z="${body_height}"/>
  </link>

  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child  link="chassis"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ================================================================== -->
  <!-- Wheels                                                              -->
  <!-- ================================================================== -->
  <!-- Rear wheels (no steering) -->
  <xacro:wheel name="rear_left_wheel"  parent="base_link"
               x="0"           y="${track_width/2}"/>
  <xacro:wheel name="rear_right_wheel" parent="base_link"
               x="0"           y="${-track_width/2}"/>

  <!-- Front wheels (with steering joints) -->
  <xacro:front_wheel name="front_left_wheel"  parent="base_link"
                     x="${wheelbase}" y="${track_width/2}"/>
  <xacro:front_wheel name="front_right_wheel" parent="base_link"
                     x="${wheelbase}" y="${-track_width/2}"/>

  <!-- ================================================================== -->
  <!-- LiDAR sensor                                                        -->
  <!-- ================================================================== -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="0.04" h="0.05"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="chassis"/>
    <child  link="lidar_link"/>
    <!-- Mount the LiDAR on top of the chassis, towards the front. -->
    <origin xyz="${wheelbase*0.6} 0 ${body_height + 0.03}" rpy="0 0 0"/>
  </joint>

  <!-- ================================================================== -->
  <!-- IMU sensor                                                          -->
  <!-- ================================================================== -->
  <link name="imu_link">
    <xacro:box_inertia m="0.01" x="0.02" y="0.02" z="0.01"/>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="chassis"/>
    <child  link="imu_link"/>
    <origin xyz="${wheelbase/2} 0 ${body_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ================================================================== -->
  <!-- RGB camera sensor                                                   -->
  <!-- ================================================================== -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.06 0.04 0.04"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.1 0.9 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.06 0.04 0.04"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.03" x="0.06" y="0.04" z="0.04"/>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="chassis"/>
    <child  link="camera_link"/>
    <origin xyz="${wheelbase + 0.03} 0 ${body_height + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- ================================================================== -->
  <!-- Gazebo plugins                                                      -->
  <!-- ================================================================== -->

  <!-- Gazebo Sim Ackermann steering system -->
  <gazebo>
    <plugin filename="gz-sim-ackermann-steering-system"
            name="gz::sim::systems::AckermannSteering">
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <left_steering_joint>front_left_wheel_steering_joint</left_steering_joint>
      <right_steering_joint>front_right_wheel_steering_joint</right_steering_joint>
      <wheel_separation>${track_width}</wheel_separation>
      <wheel_base>${wheelbase}</wheel_base>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <steering_limit>0.5</steering_limit>
      <max_velocity>2.0</max_velocity>
      <odom_publish_frequency>100</odom_publish_frequency>
      <sub_topic>/cmd_vel</sub_topic>
      <odom_topic>/odom</odom_topic>
      <tf_topic>/tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
  </gazebo>

  <!-- 2-D LiDAR sensor (bridged with ros_gz_bridge) -->
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <topic>/scan</topic>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>10.0</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
    </sensor>
  </gazebo>

  <!-- IMU sensor (bridged with ros_gz_bridge) -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <topic>/imu</topic>
      <imu>
        <angular_velocity>
          <x><noise type="gaussian"><mean>0</mean><stddev>0.009</stddev></noise></x>
          <y><noise type="gaussian"><mean>0</mean><stddev>0.009</stddev></noise></y>
          <z><noise type="gaussian"><mean>0</mean><stddev>0.009</stddev></noise></z>
        </angular_velocity>
        <linear_acceleration>
          <x><noise type="gaussian"><mean>0</mean><stddev>0.021</stddev></noise></x>
          <y><noise type="gaussian"><mean>0</mean><stddev>0.021</stddev></noise></y>
          <z><noise type="gaussian"><mean>0</mean><stddev>0.021</stddev></noise></z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- RGB camera sensor (bridged with ros_gz_bridge) -->
  <gazebo reference="camera_link">
    <sensor name="rgb_camera" type="camera">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>30</update_rate>
      <topic>/camera/image_raw</topic>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>50.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

</robot>
